alias nv="nvim"
alias t="taskwarrior-tui"
alias mail="kermit -t Mail -e neomutt"
alias calendar="kermit -t Calendar -e ikhal"
alias hdmi="xrandr --output HDMI1 --auto --right-of $(xrandr | grep -w connected | head -n 1 | cut -d " " -f 1)"
alias hdmi-off="xrandr --output HDMI1 --off"
