alias nv="nvim"
alias t="taskwarrior-tui"
alias mail="kermit -t Mail -e neomutt"
alias calendar="kermit -t Calendar -e ikhal"
alias hdmi="xrandr --output HDMI1 --auto --right-of eDP1"
alias hdmi-off="xrandr --output HDMI1 --off"
